server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Acl-service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
  application:
    name: Acl-Service